apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-fetching-app
  namespace: apps
spec:
  selector:
    matchLabels:
      app: example-fetching-app
  replicas: 1
  template:
    metadata:
      labels:
        app: example-fetching-app
    spec:
      containers:
        - name: example-fetching-app
          image: $IMAGE_NAME
          ports:
            - containerPort: 400
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
